in:
  type: file
  path_prefix: ./data/sample.csv
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: date, type: timestamp, format: '%Y-%m-%d'}
    - {name: item, type: string}
    - {name: quantity, type: long}
    - {name: price, type: long}
    - {name: total_price, type: long}
out: {type: stdout}
